// Generated by gencpp from file maskor_turtlesim/Kill.msg
// DO NOT EDIT!


#ifndef MASKOR_TURTLESIM_MESSAGE_KILL_H
#define MASKOR_TURTLESIM_MESSAGE_KILL_H

#include <ros/service_traits.h>


#include <maskor_turtlesim/KillRequest.h>
#include <maskor_turtlesim/KillResponse.h>


namespace maskor_turtlesim
{

struct Kill
{

typedef KillRequest Request;
typedef KillResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Kill
} // namespace maskor_turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maskor_turtlesim::Kill > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::maskor_turtlesim::Kill&) { return value(); }
};

template<>
struct DataType< ::maskor_turtlesim::Kill > {
  static const char* value()
  {
    return "maskor_turtlesim/Kill";
  }

  static const char* value(const ::maskor_turtlesim::Kill&) { return value(); }
};


// service_traits::MD5Sum< ::maskor_turtlesim::KillRequest> should match
// service_traits::MD5Sum< ::maskor_turtlesim::Kill >
template<>
struct MD5Sum< ::maskor_turtlesim::KillRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maskor_turtlesim::Kill >::value();
  }
  static const char* value(const ::maskor_turtlesim::KillRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maskor_turtlesim::KillRequest> should match
// service_traits::DataType< ::maskor_turtlesim::Kill >
template<>
struct DataType< ::maskor_turtlesim::KillRequest>
{
  static const char* value()
  {
    return DataType< ::maskor_turtlesim::Kill >::value();
  }
  static const char* value(const ::maskor_turtlesim::KillRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maskor_turtlesim::KillResponse> should match
// service_traits::MD5Sum< ::maskor_turtlesim::Kill >
template<>
struct MD5Sum< ::maskor_turtlesim::KillResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maskor_turtlesim::Kill >::value();
  }
  static const char* value(const ::maskor_turtlesim::KillResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maskor_turtlesim::KillResponse> should match
// service_traits::DataType< ::maskor_turtlesim::Kill >
template<>
struct DataType< ::maskor_turtlesim::KillResponse>
{
  static const char* value()
  {
    return DataType< ::maskor_turtlesim::Kill >::value();
  }
  static const char* value(const ::maskor_turtlesim::KillResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASKOR_TURTLESIM_MESSAGE_KILL_H
