// Generated by gencpp from file maskor_turtlesim/SetPen.msg
// DO NOT EDIT!


#ifndef MASKOR_TURTLESIM_MESSAGE_SETPEN_H
#define MASKOR_TURTLESIM_MESSAGE_SETPEN_H

#include <ros/service_traits.h>


#include <maskor_turtlesim/SetPenRequest.h>
#include <maskor_turtlesim/SetPenResponse.h>


namespace maskor_turtlesim
{

struct SetPen
{

typedef SetPenRequest Request;
typedef SetPenResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPen
} // namespace maskor_turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maskor_turtlesim::SetPen > {
  static const char* value()
  {
    return "9f452acce566bf0c0954594f69a8e41b";
  }

  static const char* value(const ::maskor_turtlesim::SetPen&) { return value(); }
};

template<>
struct DataType< ::maskor_turtlesim::SetPen > {
  static const char* value()
  {
    return "maskor_turtlesim/SetPen";
  }

  static const char* value(const ::maskor_turtlesim::SetPen&) { return value(); }
};


// service_traits::MD5Sum< ::maskor_turtlesim::SetPenRequest> should match
// service_traits::MD5Sum< ::maskor_turtlesim::SetPen >
template<>
struct MD5Sum< ::maskor_turtlesim::SetPenRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maskor_turtlesim::SetPen >::value();
  }
  static const char* value(const ::maskor_turtlesim::SetPenRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maskor_turtlesim::SetPenRequest> should match
// service_traits::DataType< ::maskor_turtlesim::SetPen >
template<>
struct DataType< ::maskor_turtlesim::SetPenRequest>
{
  static const char* value()
  {
    return DataType< ::maskor_turtlesim::SetPen >::value();
  }
  static const char* value(const ::maskor_turtlesim::SetPenRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maskor_turtlesim::SetPenResponse> should match
// service_traits::MD5Sum< ::maskor_turtlesim::SetPen >
template<>
struct MD5Sum< ::maskor_turtlesim::SetPenResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maskor_turtlesim::SetPen >::value();
  }
  static const char* value(const ::maskor_turtlesim::SetPenResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maskor_turtlesim::SetPenResponse> should match
// service_traits::DataType< ::maskor_turtlesim::SetPen >
template<>
struct DataType< ::maskor_turtlesim::SetPenResponse>
{
  static const char* value()
  {
    return DataType< ::maskor_turtlesim::SetPen >::value();
  }
  static const char* value(const ::maskor_turtlesim::SetPenResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASKOR_TURTLESIM_MESSAGE_SETPEN_H
