// Generated by gencpp from file maskor_turtlesim/Spawn.msg
// DO NOT EDIT!


#ifndef MASKOR_TURTLESIM_MESSAGE_SPAWN_H
#define MASKOR_TURTLESIM_MESSAGE_SPAWN_H

#include <ros/service_traits.h>


#include <maskor_turtlesim/SpawnRequest.h>
#include <maskor_turtlesim/SpawnResponse.h>


namespace maskor_turtlesim
{

struct Spawn
{

typedef SpawnRequest Request;
typedef SpawnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Spawn
} // namespace maskor_turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maskor_turtlesim::Spawn > {
  static const char* value()
  {
    return "0b2d2e872a8e2887d5ed626f2bf2c561";
  }

  static const char* value(const ::maskor_turtlesim::Spawn&) { return value(); }
};

template<>
struct DataType< ::maskor_turtlesim::Spawn > {
  static const char* value()
  {
    return "maskor_turtlesim/Spawn";
  }

  static const char* value(const ::maskor_turtlesim::Spawn&) { return value(); }
};


// service_traits::MD5Sum< ::maskor_turtlesim::SpawnRequest> should match
// service_traits::MD5Sum< ::maskor_turtlesim::Spawn >
template<>
struct MD5Sum< ::maskor_turtlesim::SpawnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maskor_turtlesim::Spawn >::value();
  }
  static const char* value(const ::maskor_turtlesim::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maskor_turtlesim::SpawnRequest> should match
// service_traits::DataType< ::maskor_turtlesim::Spawn >
template<>
struct DataType< ::maskor_turtlesim::SpawnRequest>
{
  static const char* value()
  {
    return DataType< ::maskor_turtlesim::Spawn >::value();
  }
  static const char* value(const ::maskor_turtlesim::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maskor_turtlesim::SpawnResponse> should match
// service_traits::MD5Sum< ::maskor_turtlesim::Spawn >
template<>
struct MD5Sum< ::maskor_turtlesim::SpawnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maskor_turtlesim::Spawn >::value();
  }
  static const char* value(const ::maskor_turtlesim::SpawnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maskor_turtlesim::SpawnResponse> should match
// service_traits::DataType< ::maskor_turtlesim::Spawn >
template<>
struct DataType< ::maskor_turtlesim::SpawnResponse>
{
  static const char* value()
  {
    return DataType< ::maskor_turtlesim::Spawn >::value();
  }
  static const char* value(const ::maskor_turtlesim::SpawnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASKOR_TURTLESIM_MESSAGE_SPAWN_H
