// Generated by gencpp from file maskor_turtlesim/SpawnRequest.msg
// DO NOT EDIT!


#ifndef MASKOR_TURTLESIM_MESSAGE_SPAWNREQUEST_H
#define MASKOR_TURTLESIM_MESSAGE_SPAWNREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maskor_turtlesim
{
template <class ContainerAllocator>
struct SpawnRequest_
{
  typedef SpawnRequest_<ContainerAllocator> Type;

  SpawnRequest_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , name()  {
    }
  SpawnRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SpawnRequest_

typedef ::maskor_turtlesim::SpawnRequest_<std::allocator<void> > SpawnRequest;

typedef boost::shared_ptr< ::maskor_turtlesim::SpawnRequest > SpawnRequestPtr;
typedef boost::shared_ptr< ::maskor_turtlesim::SpawnRequest const> SpawnRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maskor_turtlesim::SpawnRequest_<ContainerAllocator1> & lhs, const ::maskor_turtlesim::SpawnRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maskor_turtlesim::SpawnRequest_<ContainerAllocator1> & lhs, const ::maskor_turtlesim::SpawnRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maskor_turtlesim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57f001c49ab7b11d699f8606c1f4f7ff";
  }

  static const char* value(const ::maskor_turtlesim::SpawnRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57f001c49ab7b11dULL;
  static const uint64_t static_value2 = 0x699f8606c1f4f7ffULL;
};

template<class ContainerAllocator>
struct DataType< ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maskor_turtlesim/SpawnRequest";
  }

  static const char* value(const ::maskor_turtlesim::SpawnRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 theta\n"
"string name # Optional.  A unique name will be created and returned if this is empty\n"
;
  }

  static const char* value(const ::maskor_turtlesim::SpawnRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpawnRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maskor_turtlesim::SpawnRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maskor_turtlesim::SpawnRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASKOR_TURTLESIM_MESSAGE_SPAWNREQUEST_H
