// Generated by gencpp from file maskor_turtlesim/TeleportRelative.msg
// DO NOT EDIT!


#ifndef MASKOR_TURTLESIM_MESSAGE_TELEPORTRELATIVE_H
#define MASKOR_TURTLESIM_MESSAGE_TELEPORTRELATIVE_H

#include <ros/service_traits.h>


#include <maskor_turtlesim/TeleportRelativeRequest.h>
#include <maskor_turtlesim/TeleportRelativeResponse.h>


namespace maskor_turtlesim
{

struct TeleportRelative
{

typedef TeleportRelativeRequest Request;
typedef TeleportRelativeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TeleportRelative
} // namespace maskor_turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maskor_turtlesim::TeleportRelative > {
  static const char* value()
  {
    return "9d5c2dcd348ac8f76ce2a4307bd63a13";
  }

  static const char* value(const ::maskor_turtlesim::TeleportRelative&) { return value(); }
};

template<>
struct DataType< ::maskor_turtlesim::TeleportRelative > {
  static const char* value()
  {
    return "maskor_turtlesim/TeleportRelative";
  }

  static const char* value(const ::maskor_turtlesim::TeleportRelative&) { return value(); }
};


// service_traits::MD5Sum< ::maskor_turtlesim::TeleportRelativeRequest> should match
// service_traits::MD5Sum< ::maskor_turtlesim::TeleportRelative >
template<>
struct MD5Sum< ::maskor_turtlesim::TeleportRelativeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maskor_turtlesim::TeleportRelative >::value();
  }
  static const char* value(const ::maskor_turtlesim::TeleportRelativeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maskor_turtlesim::TeleportRelativeRequest> should match
// service_traits::DataType< ::maskor_turtlesim::TeleportRelative >
template<>
struct DataType< ::maskor_turtlesim::TeleportRelativeRequest>
{
  static const char* value()
  {
    return DataType< ::maskor_turtlesim::TeleportRelative >::value();
  }
  static const char* value(const ::maskor_turtlesim::TeleportRelativeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maskor_turtlesim::TeleportRelativeResponse> should match
// service_traits::MD5Sum< ::maskor_turtlesim::TeleportRelative >
template<>
struct MD5Sum< ::maskor_turtlesim::TeleportRelativeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maskor_turtlesim::TeleportRelative >::value();
  }
  static const char* value(const ::maskor_turtlesim::TeleportRelativeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maskor_turtlesim::TeleportRelativeResponse> should match
// service_traits::DataType< ::maskor_turtlesim::TeleportRelative >
template<>
struct DataType< ::maskor_turtlesim::TeleportRelativeResponse>
{
  static const char* value()
  {
    return DataType< ::maskor_turtlesim::TeleportRelative >::value();
  }
  static const char* value(const ::maskor_turtlesim::TeleportRelativeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASKOR_TURTLESIM_MESSAGE_TELEPORTRELATIVE_H
