// Generated by gencpp from file maskor_turtlesim/TeleportAbsolute.msg
// DO NOT EDIT!


#ifndef MASKOR_TURTLESIM_MESSAGE_TELEPORTABSOLUTE_H
#define MASKOR_TURTLESIM_MESSAGE_TELEPORTABSOLUTE_H

#include <ros/service_traits.h>


#include <maskor_turtlesim/TeleportAbsoluteRequest.h>
#include <maskor_turtlesim/TeleportAbsoluteResponse.h>


namespace maskor_turtlesim
{

struct TeleportAbsolute
{

typedef TeleportAbsoluteRequest Request;
typedef TeleportAbsoluteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TeleportAbsolute
} // namespace maskor_turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maskor_turtlesim::TeleportAbsolute > {
  static const char* value()
  {
    return "a130bc60ee6513855dc62ea83fcc5b20";
  }

  static const char* value(const ::maskor_turtlesim::TeleportAbsolute&) { return value(); }
};

template<>
struct DataType< ::maskor_turtlesim::TeleportAbsolute > {
  static const char* value()
  {
    return "maskor_turtlesim/TeleportAbsolute";
  }

  static const char* value(const ::maskor_turtlesim::TeleportAbsolute&) { return value(); }
};


// service_traits::MD5Sum< ::maskor_turtlesim::TeleportAbsoluteRequest> should match
// service_traits::MD5Sum< ::maskor_turtlesim::TeleportAbsolute >
template<>
struct MD5Sum< ::maskor_turtlesim::TeleportAbsoluteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maskor_turtlesim::TeleportAbsolute >::value();
  }
  static const char* value(const ::maskor_turtlesim::TeleportAbsoluteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maskor_turtlesim::TeleportAbsoluteRequest> should match
// service_traits::DataType< ::maskor_turtlesim::TeleportAbsolute >
template<>
struct DataType< ::maskor_turtlesim::TeleportAbsoluteRequest>
{
  static const char* value()
  {
    return DataType< ::maskor_turtlesim::TeleportAbsolute >::value();
  }
  static const char* value(const ::maskor_turtlesim::TeleportAbsoluteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maskor_turtlesim::TeleportAbsoluteResponse> should match
// service_traits::MD5Sum< ::maskor_turtlesim::TeleportAbsolute >
template<>
struct MD5Sum< ::maskor_turtlesim::TeleportAbsoluteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maskor_turtlesim::TeleportAbsolute >::value();
  }
  static const char* value(const ::maskor_turtlesim::TeleportAbsoluteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maskor_turtlesim::TeleportAbsoluteResponse> should match
// service_traits::DataType< ::maskor_turtlesim::TeleportAbsolute >
template<>
struct DataType< ::maskor_turtlesim::TeleportAbsoluteResponse>
{
  static const char* value()
  {
    return DataType< ::maskor_turtlesim::TeleportAbsolute >::value();
  }
  static const char* value(const ::maskor_turtlesim::TeleportAbsoluteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASKOR_TURTLESIM_MESSAGE_TELEPORTABSOLUTE_H
